// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrYeNwjL1qZxZ7_crrOgINZMwl1WLqk0A',
    appId: '1:520183629776:web:e6323314100918dff79bd5',
    messagingSenderId: '520183629776',
    projectId: 'arco-health',
    authDomain: 'arco-health.firebaseapp.com',
    storageBucket: 'arco-health.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVu8ri3kNioWbOiVlX8-MzZplYBc8_Rg',
    appId: '1:520183629776:android:7fa150b493b4ddebf79bd5',
    messagingSenderId: '520183629776',
    projectId: 'arco-health',
    storageBucket: 'arco-health.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACB2otvFXZqXFMWOM3Vjnxfghvl8PIxrI',
    appId: '1:520183629776:ios:90f9cbc6b92414b8f79bd5',
    messagingSenderId: '520183629776',
    projectId: 'arco-health',
    storageBucket: 'arco-health.appspot.com',
    iosClientId: '520183629776-5pg8p6dl4qatqmj858bhdt6u02fp4f9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.arcoDev',
  );
}
